### ISSUE TITLE
Attribute Error when starting hdf5view

### ISSUE THREAD

**Issue by schmampf** [marts/hdf5view#12]
Hi there,
I'm new to this, but I got a problem when I called hdf5view. When I removed the line, it worked quite fine for me. Is there something I'm missing? Thanks a lot!
Best Regards, Oliver

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/hdf5view", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hdf5view/main.py", line 74, in main
    window.open_file(args.file)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hdf5view/mainwindow.py", line 269, in open_file
    hdf_widget = HDF5Widget(hdf)
                 ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hdf5view/views.py", line 114, in __init__
    self.tabs.tabBar().tabButton(0, QTabBar.RightSide).deleteLater()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'deleteLater'

**Comment by marts** [comment]
Hi @schmampf to be honest, I can't remember why that line is there. It might have been because an older version of Qt worked in a different way when initialising tabs, or it could just be a bug ... I may have been trying to stop a memory leak or something.

But I have reproduced the bug (on my MacBook)...wonder if it's specific to that OS.

Basically it looks like `self.tabs.tabBar().tabButton(0, QTabBar.RightSide)` is None and therefore doesn't have the attribute 'deleteLater' so there is no point in calling it.

Therefore the code could be changed to:
```
if self.tabs.tabBar().tabButton(0, QTabBar.RightSide):
    self.tabs.tabBar().tabButton(0, QTabBar.RightSide).deleteLater()
```

Or possibly removed altogether.

I don't actually use hdf5view anymore (I used to work with very large MEG datasets). It's more actively maintened by @tgwoodcock ... I just happen to still host the project :)

@tgwoodcock have you ever seen this error before?

**Comment by tgwoodcock** [comment]
Hi @schmampf, thanks for bringing this to our attention. Can you please let us know what OS you are using and the version of whichever Qt-bindings you are using (pyqt5 / pyside2 / pyq6 / pyside6)? This might help to understand where this is coming from.

I haven't seen this on Windows before, @marts but I don't have any feedback about other OS.

**Comment by schmampf** [comment]
Hi @marts @tgwoodcock,
Thanks a lot for your nice replies! My Operating System is MacOS Sonoma 14.6.1.
I was super confused how to install hdf5view, so I wanted to make sure to make it run. In the end I installed: pyqt5, pyqt6, pyside6
Hope that helps!

**Comment by tgwoodcock** [comment]
I've tested hdf5view 0.1.1 on Windows10 with Python 3.12.2 with PyQt5 and PyQt6 and cannot reproduce the error. (PySide2 does not work with Python12 and using PySide6 resulted in a separate error (see issue #13).)

The tests were done with
- QtPy               2.4.1
- PyQt6-6.7.1
- PyQt5-5.15.11

@marts, @schmampf, can you please post the versions of QtPy and the Python Qt bindings you have tried? @schmampf: if you have several Qt bindings installed, QtPy should take PyQt5 first to run hdf5view. Thanks.

**Comment by schmampf** [comment]
@tgwoodcock my only difference is the version of Python and the Operating System.
- MacOS Sonoma 14.6.1
- Python 3.12.3
- hdf5view 0.1.1
- QtPy 2.4.1
- PyQt6 6.7.1
- PyQt 5.15.11

**Comment by marts** [comment]
I built a development version in a venv on MacOS Sonoma 14.6.1 with Python 3.12.5
```
pip list
Package   Version Editable project location
--------- ------- ----------------------------------------
h5py      3.11.0
hdf5view  0.1.1   /Users/martinswarbrick/projects/hdf5view
numpy     2.1.1
packaging 24.1
pip       24.2
psutil    6.0.0
PyQt5     5.15.11
PyQt5-Qt5 5.15.15
PyQt5_sip 12.15.0
pyqtgraph 0.13.7
QtPy      2.4.1
```

**Comment by tgwoodcock** [comment]
Thanks for your replies @marts and @schmampf.

I've looked into it a bit more and I think we can just remove the line. The block of code is lines 107 to 116 (inclusive) in hdf5view/views.py:

```
# Setup tabs
self.tabs = QTabWidget()
self.tabs.setTabPosition(QTabWidget.South)
self.tabs.setTabsClosable(True)

self.tabs.addTab(self.data_view, 'Table')

self.tabs.tabBar().tabButton(0, QTabBar.RightSide).deleteLater()
self.tabs.tabBar().setTabButton(0, QTabBar.RightSide, None)
self.tabs.tabCloseRequested.connect(self.handle_close_tab)
```

As @marts said, on MAC, we have the problem that `self.tabs.tabBar().tabButton(0, QTabBar.RightSide)` is None. On Windows10, this appears to be a PyQt5.QtWidgets.QAbstractButton. Why there should be a difference between the two OS is not clear to me. 

In any case, the next line: `self.tabs.tabBar().setTabButton(0, QTabBar.RightSide, None)` then sets the widget at index 0 and location QTabBar.RightSide to None. This means that the 'table' tab does not have a 'close' button - this is desired behaviour as the 'table' tab is always there. In this case, I think we can safely remove the line `self.tabs.tabBar().tabButton(0, QTabBar.RightSide).deleteLater()` without any effect.

Unless there are any final comments, I'll simply push this change onto the 'main' branch and then it will go into the next version at some later date.
